# Generated by Django 3.2.9 on 2021-11-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211104_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
