# Generated by Django 3.2.9 on 2021-11-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
